spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://<>.mysql.database.azure.com:3306/wulei?useSSL=true&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: <>
    password: <>
  jpa:
    hibernate:
      ddl-auto: update
management:
  server:
    servlet:
      context-path: /management