spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://<>.mysql.database.azure.com:3306/wulei?useSSL=true&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: <>
    password: <>
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 443
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: info, health, httptrace
  endpoint:
    httptrace:
      enabled: true
logging:
  level:
    org:
      springframework:
        web: INFO