spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wulei?verifyServerCertificate=true&useSSL=true&requireSSL=true&clientCertificateKeyStoreUrl=file:mysql_ssl/keystore&clientCertificateKeyStorePassword=&trustCertificateKeyStoreUrl=file:mysql_ssl/truststore&trustCertificateKeyStorePassword=&useUnicode=yes&characterEncoding=UTF-8
    username: wulei_server_admin
    password: atrx
  jpa:
    hibernate:
      ddl-auto: update
management:
  context-path: /management